baseURL = "https://alexigugushvili.org/"
languageCode = "en-us"
title = "Alexi Gugushvili"


[params]
  description = "Professor of Sociology, University of Oslo"
  author = "Alexi Gugushvili"
  googleScholar = "https://scholar.google.com/citations?user=i8GjBdQAAAAJ"
  researchGate = "https://www.researchgate.net/profile/Alexi-Gugushvili-2"
  orcid = "https://orcid.org/0000-0002-3933-9111"
  email = "alexi.gugushvili@sosgeo.uio.no"
  uio = "https://www.sv.uio.no/iss/english/people/aca/alexig/"
  bluesky = "https://bsky.app/profile/a-gugushvili.bsky.social"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 4
  [[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 5
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML"]

